{
 "title": "Pomerium",
 "tags": [ "pomerium" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pomerium Policies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomerium_policy_count_total" }
   ]
  },
  {
   "title": "Identity Manager - Last Refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pomerium_identity_manager_last_refresh_timestamp*1000"
    }
   ]
  },
  {
   "title": "Identity Manager - Last User Refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pomerium_identity_manager_last_user_refresh_success_timestamp*1000"
    }
   ]
  },
  {
   "title": "Autocert - Certificates Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pomerium_autocert_certificates_total)"
    }
   ]
  },
  {
   "title": "Autocert - Certificate Next Expire",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pomerium_autocert_certificate_next_expires_seconds"
    }
   ]
  },
  {
   "title": "Autocert - Certificate Renewals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pomerium_autocert_renewals_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Pomerium Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "pomerium_build_info" }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "rate(pomerium_http_server_request_duration_ms_sum[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP - Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pomerium_http_server_request_size_bytes_sum[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP - Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pomerium_http_server_requests_total[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP - Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pomerium_http_server_response_size_bytes_sum[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "GRPC Client Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_client_request_size_bytes_sum[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Client Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_client_response_size_bytes_sum[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Client Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_client_request_duration_ms_sum{}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Client Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 35 },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_client_requests_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Server Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_server_request_size_bytes_sum[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Server Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_server_response_size_bytes_sum[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Server Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_server_request_duration_ms_sum{}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "GRPC Server Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 51 },
     "targets": [
      {
       "expr": "rate(pomerium_grpc_server_requests_total[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}