# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: Check for license presence
kind: pipeline
type: docker

steps:
  - name: check
    image: docker.io/library/golang:1.20
    pull: always
    commands:
      - go install github.com/google/addlicense@v1.1.1
      - addlicense -c "SIGHUP s.r.l" -v -l bsd -y "2017-present" --check .

---
name: Linting
kind: pipeline
type: docker

depends_on:
  - Check for license presence

platform:
  os: linux
  arch: amd64

steps:
  - name: Linting with Policeman
    image: quay.io/sighup/policeman
    pull: always
    environment:
      FILTER_REGEX_EXCLUDE: (\.github)
      # Identifies false positives like missing 'selector'.
      # Doing this is valid for Kustomize patches
      VALIDATE_KUBERNETES_KUBEVAL: "false"
      # Some duplicated code is intended.
      VALIDATE_JSCPD: "false"
      # hadolint already validated dockerfiles
      VALIDATE_DOCKERFILE: "false"
      # Disable natural language checks
      VALIDATE_NATURAL_LANGUAGE: "false"
      # Disable html checks
      VALIDATE_HTML: "false"
      # Disable css checks
      VALIDATE_CSS: "false"
    depends_on:
      - clone

  - name: Render Manifests
    image: quay.io/sighup/e2e-testing:1.1.0_0.11.0_3.12.0_1.9.4_1.27.1_3.5.3_4.33.3
    pull: always
    depends_on:
      - clone
    commands:
      - kustomize build katalog/pomerium > pomerium.yml
      - kustomize build katalog/dex > dex.yml
      - kustomize build katalog/gangplank > gangplank.yml

  - name: Check for usage of deprecated APIs
    image: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5
    pull: always
    depends_on:
      - Render Manifests
    commands:
      # we use --ignore-deprecations because we don't want the CI to fail when the API has not been removed yet.
      - /pluto detect pomerium.yml --ignore-deprecations --target-versions=k8s=v1.31.0
      - /pluto detect dex.yml --ignore-deprecations --target-versions=k8s=v1.31.0
      - /pluto detect gangplank.yml --ignore-deprecations --target-versions=k8s=v1.31.0

---
name: E2E Tests Kubernetes v1.28.13
kind: pipeline
type: docker

depends_on:
  - Linting

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    pull: always
    depends_on:
      - clone
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      # KIND_CONFIG: ./katalog/tests/kind/config.yml
      CLUSTER_VERSION: v1.28.13
      KUBECONFIG: kubeconfig-v1.28.13
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.28.13
    commands:
      # NOTE: kind's `--wait` flag that waits for the control-plane to be ready
      # does not work when disabling the default CNI. It will always go in timeout.
      - kind create cluster --name $${CLUSTER_NAME} --image registry.sighup.io/fury/kindest/node:$${CLUSTER_VERSION} # --config $${KIND_CONFIG}
      # save the kubeconfig so we can use it from other steps.
      - kind get kubeconfig --name $${CLUSTER_NAME} > $${KUBECONFIG}

  - name: End-to-End Tests
    image: quay.io/sighup/e2e-testing:1.1.0_1.31.1_3.10.0_4.33.3
    pull: always
    network_mode: host
    environment:
      KUBECONFIG: kubeconfig-v1.28.13
    depends_on:
      - Create Kind Cluster
    commands:
      # wait for Kind cluster to be ready
      - until kubectl get serviceaccount default > /dev/null 2>&1; do echo "waiting for control-plane" && sleep 1; done
      - bats -t katalog/tests/tests.sh

  - name: Destroy Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.28.13
    commands:
      # does not matter if the command fails
      - kind delete cluster --name $${CLUSTER_NAME} || true
    depends_on:
      - End-to-End Tests
    when:
      status:
        - success
        - failure

---
name: E2E Tests Kubernetes v1.29.8
kind: pipeline
type: docker

depends_on:
  - Linting

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    pull: always
    depends_on:
      - clone
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      # KIND_CONFIG: ./katalog/tests/kind/config.yml
      CLUSTER_VERSION: v1.29.8
      KUBECONFIG: kubeconfig-v1.29.8
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.29.8
    commands:
      # NOTE: kind's `--wait` flag that waits for the control-plane to be ready
      # does not work when disabling the default CNI. It will always go in timeout.
      - kind create cluster --name $${CLUSTER_NAME} --image registry.sighup.io/fury/kindest/node:$${CLUSTER_VERSION} # --config $${KIND_CONFIG}
      # save the kubeconfig so we can use it from other steps.
      - kind get kubeconfig --name $${CLUSTER_NAME} > $${KUBECONFIG}

  - name: End-to-End Tests
    image: quay.io/sighup/e2e-testing:1.1.0_1.31.1_3.10.0_4.33.3
    pull: always
    network_mode: host
    environment:
      KUBECONFIG: kubeconfig-v1.29.8
    depends_on:
      - Create Kind Cluster
    commands:
      # wait for Kind cluster to be ready
      - until kubectl get serviceaccount default > /dev/null 2>&1; do echo "waiting for control-plane" && sleep 1; done
      - bats -t katalog/tests/tests.sh

  - name: Destroy Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.29.8
    commands:
      # does not matter if the command fails
      - kind delete cluster --name $${CLUSTER_NAME} || true
    depends_on:
      - End-to-End Tests
    when:
      status:
        - success
        - failure

---
name: E2E Tests Kubernetes v1.30.4
kind: pipeline
type: docker

depends_on:
  - Linting

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    pull: always
    depends_on:
      - clone
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      # KIND_CONFIG: ./katalog/tests/kind/config.yml
      CLUSTER_VERSION: v1.30.4
      KUBECONFIG: kubeconfig-v1.30.4
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.30.4
    commands:
      # NOTE: kind's `--wait` flag that waits for the control-plane to be ready
      # does not work when disabling the default CNI. It will always go in timeout.
      - kind create cluster --name $${CLUSTER_NAME} --image registry.sighup.io/fury/kindest/node:$${CLUSTER_VERSION} # --config $${KIND_CONFIG}
      # save the kubeconfig so we can use it from other steps.
      - kind get kubeconfig --name $${CLUSTER_NAME} > $${KUBECONFIG}

  - name: End-to-End Tests
    image: quay.io/sighup/e2e-testing:1.1.0_1.31.1_3.10.0_4.33.3
    pull: always
    network_mode: host
    environment:
      KUBECONFIG: kubeconfig-v1.30.4
    depends_on:
      - Create Kind Cluster
    commands:
      # wait for Kind cluster to be ready
      - until kubectl get serviceaccount default > /dev/null 2>&1; do echo "waiting for control-plane" && sleep 1; done
      - bats -t katalog/tests/tests.sh

  - name: Destroy Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.30.4
    commands:
      # does not matter if the command fails
      - kind delete cluster --name $${CLUSTER_NAME} || true
    depends_on:
      - End-to-End Tests
    when:
      status:
        - success
        - failure

---
name: E2E Tests Kubernetes v1.31.0
kind: pipeline
type: docker

depends_on:
  - Linting

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    pull: always
    depends_on:
      - clone
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      # KIND_CONFIG: ./katalog/tests/kind/config.yml
      CLUSTER_VERSION: v1.31.0
      KUBECONFIG: kubeconfig-v1.31.0
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.31.0
    commands:
      # NOTE: kind's `--wait` flag that waits for the control-plane to be ready
      # does not work when disabling the default CNI. It will always go in timeout.
      - kind create cluster --name $${CLUSTER_NAME} --image registry.sighup.io/fury/kindest/node:$${CLUSTER_VERSION} # --config $${KIND_CONFIG}
      # save the kubeconfig so we can use it from other steps.
      - kind get kubeconfig --name $${CLUSTER_NAME} > $${KUBECONFIG}

  - name: End-to-End Tests
    image: quay.io/sighup/e2e-testing:1.1.0_1.31.1_3.10.0_4.33.3
    pull: always
    network_mode: host
    environment:
      KUBECONFIG: kubeconfig-v1.31.0
    depends_on:
      - Create Kind Cluster
    commands:
      # wait for Kind cluster to be ready
      - until kubectl get serviceaccount default > /dev/null 2>&1; do echo "waiting for control-plane" && sleep 1; done
      - bats -t katalog/tests/tests.sh

  - name: Destroy Kind Cluster
    image: quay.io/sighup/dind-kind-kubectl-kustomize:0.24.0_1.31.1_3.10.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      CLUSTER_NAME: ${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-v1.31.0
    commands:
      # does not matter if the command fails
      - kind delete cluster --name $${CLUSTER_NAME} || true
    depends_on:
      - End-to-End Tests
    when:
      status:
        - success
        - failure

---
name: release
kind: pipeline
type: docker

depends_on:
  - E2E Tests Kubernetes v1.28.13
  - E2E Tests Kubernetes v1.29.8
  - E2E Tests Kubernetes v1.30.4
  - E2E Tests Kubernetes v1.31.0

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: prepare-tar-gz
    image: alpine:latest
    pull: always
    depends_on: [clone]
    commands:
      - tar -zcvf fury-kubernetes-auth-${DRONE_TAG}.tar.gz katalog/ LICENSE README.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [clone]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-auth-${DRONE_TAG}.tar.gz
      prerelease: true
      overwrite: true
      title: "Preview ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-auth-${DRONE_TAG}.tar.gz
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
