# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
  labels:
    app: pomerium
spec:
  selector:
    matchLabels:
      app: pomerium
  replicas: 1
  template:
    metadata:
      labels:
        app: pomerium
    spec:
      containers:
        - name: pomerium
          image: pomerium/pomerium
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          args:
            - -config
            - /etc/pomerium/policy.yml
          envFrom:
            - secretRef:
                name: pomerium-env
            - configMapRef:
                name: pomerium
          env:
            - name: SERVICES
              value: all
            - name: INSECURE_SERVER
              value: "TRUE"
            - name: JWT_CLAIMS_HEADERS
              value: "email"
            # - name: LOG_LEVEL
            #   value: "debug"
            # - name: PROXY_LOG_LEVEL
            #   value: "debug"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            privileged: false
            runAsUser: 65532
            runAsGroup: 65532
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            # This tmp mount is needed so we can have readOnlyRootFilesystem: true
            - name: tmp
              mountPath: /tmp
            - mountPath: /etc/pomerium/
              name: pomerium-policy
      volumes:
        - configMap:
            defaultMode: 420
            name: pomerium-policy
          name: pomerium-policy
        - name: tmp
          emptyDir: {}
