# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yml
  - rbac.yml
  - services.yml
  - sm.yml

images:
  - name: quay.io/keycloak/keycloak
    newName: quay.io/sighup/keycloak-metrics-spi
    newTag: 18.0.0_2.5.3
