apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sm.yml

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  disableNameSuffixHash: true

configMapGenerator:
  - name: pomerium-dashboards
    files:
      - dashboards/pomerium.json
      - dashboards/envoy.json
