apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pomerium
  namespace: pomerium-master-postgres
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: pomerium
