# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangplank
  labels:
    app: gangplank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangplank
  template:
    metadata:
      labels:
        app: gangplank
    spec:
      containers:
        - name: gangplank
          image: "registry.sighup.io/fury/gangplank"
          imagePullPolicy: Always
          command: ["gangplank", "-config", "/gangplank/gangplank.yml"]
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - name: gangplank
              mountPath: /gangplank/
            - name: html-templates
              mountPath: /custom-templates
      volumes:
        - name: gangplank
          secret:
            secretName: gangplank
        - name: html-templates
          configMap:
            name: html-templates
---
kind: Service
apiVersion: v1
metadata:
  name: gangplank-svc
  labels:
    app: gangplank
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: gangplank
