listen: http://0.0.0.0:5555
web_path_prefix: /
debug: false
clusters:
- client_id: example-client-id
  client_secret: example-client-id-secret
  description: Example Cluser auth
  issuer: https://dex.example.io
  k8s_ca_pem: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  k8s_master_uri: https://api.kubernetes.example.io:6443
  name: ew-ci
  redirect_uri: https://this-service.example.io/callback
  short_description: Example Login Kuberntes dashboard
  logo_uri: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
